### ISSUE TITLE
Input for APT Package Dependency

### ISSUE THREAD

**Issue by threeal** [threeal/ros2-ci#9]
Create a new input for the actions that will install all packages listed in that input. For example, this configuration here will install `libssl-dev` and `libopencv-dev`.

```yaml
uses: ichiro-its/ros2-ci@v0.3.0
  with:
    ros2-distro: foxy
    apt-packages: libssl-dev libopencv-dev
```

Additionally, specify new inputs `pre-install` and `post-install` that will run commands before and after apt install respectively.
